apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercontagem
spec:
  selector:
    matchLabels:
      app: workercontagem
  replicas: 1
  template:
    metadata:
      labels:
        app: workercontagem
    spec:
      containers:
      - name: workercontagem
        image: renatogroffe/workercontagem-kafka-dotnet6:1
        env:
        - name: ApacheKafka__Topic
          value: topic-contagem
        - name: ApacheKafka__GroupId
          value: workercontagem
        - name: ApacheKafka__Host
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: HostKafka
        - name: ConnectionStrings__BaseContagem
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionSqlServer